openapi: 3.0.4
info:
  title: Iglu Cache API
  description: |-
    This is the documentation of the Iglu Cache API. This Cache is part of the [Iglu Project](https://github.com/iglu-sh).
  version: 0.0.1

servers:
  - url: https://example.com/api/v1
paths:
  /cache/{cache}:
    parameters:
    - in: path
      name: cache
      schema:
        type: string
      required: true
      description: Name of the Cache
    get:
      summary: Get information of {cache} 
      description: |-
        Get information about {cache}
      responses:
        "405":
          description: Method not allowed
          content:
            text/plain:
              schema:
                type: string
                example: Method Not Allowed
        "404":
          description: Cache Not Found
          content:
            text/plain:
              schema:
                type: string
                example: Cache Not Found
        "400":
          description: No public signing key
          content:
            text/plain:
              schema:
                type: string
                example: There is no public signing key for this cache, add one by using cachix generate-keypair {cache}
        "200":
          description: Information about the cache
          content:
            application/json:
              schema:
                type: object
                properties:
                  githubUsername:
                    type: string
                    example: user
                  isPublic:
                    type: boolean
                    example: false
                  name:
                    type: string
                    example: default
                  permission:
                    type: string
                    example: Read
                  preferredCompressionMethod:
                    type: string
                    example: zstd
                  publicSigningKeys:
                    type: array
                    items:
                      type: string
                      example: default:N70oHEuy1jSzIZ5xEZdqCv4/49KERecq/P3sleSLxjI=
                  uri:
                    type: string
                    example: http://example.com
                  priority:
                    type: number
                    example: 40
        "500":
          description: Internal Server Error
          content:
            plain/text:
              schema:
                type: string
                example: Internal Server Error
          
